version: "3.7"

x-common: &common
  build:
    context: .

services:

  tests:
    <<: *common
    volumes:
    - ./sattl:/app/sattl
    - ./tests:/app/tests

  sattl:
    <<: *common
    volumes:
      - ./sattl:/app/sattl
      - ./config.json:/app/config.json:ro
    build:
      target: base
