version: "3.7"

x-common: &common
  volumes:
    - ./sattl:/app/sattl
    - ./config.json:/app/config.json:ro

services:

  tests:
    <<: *common
    volumes:
    - ./tests:/app/tests
    build: &build
      context: .

  sattl:
    <<: *common
    build:
      <<: *build
      target: base
