services:
  tests:
    build:
      context: .
    volumes:
      - ./sattl:/app/sattl
      - ./tests:/app/tests

  sattl:
    build:
      context: .
      target: base
    volumes:
      - ./sattl:/app/sattl
      - ./config.json:/app/config.json:ro
