version: "3.7"

services:

  tests:
    volumes:
    - ./sattl:/app/sattl
    - ./tests:/app/tests
    build:
      context: .

  sattl:
    volumes:
      - ./sattl:/app/sattl
      - ./config.json:/app/config.json:ro
    build:
      target: base
