name: SATTL
on: push

jobs:
  sattl-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install system requirements
      run: |
        sudo apt-get update -y
        sudo apt-get -y -qq install --no-install-recommends build-essential
    - name: Copy test config
      run: cp .github/workflows/config.json.sample config.json
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.cfg') }}
    - name: Setup dependencies
      run: |
        pip install -i https://tech-pypi-prod.2u.com/simple -e .
        pip install -i https://tech-pypi-prod.2u.com/simple '.[testing]'
    - name: Run tests
      run: python -m pytest

  build-and-push:
    needs: sattl-tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY:  enrollment-systems/sattl
      run: |
#        cd ..
        export TAG=${GITHUB_REF##*/}
        echo $TAG
        tree
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
