name: SATTL
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Run tests
      run: docker-compose run tests

  build-and-push:
    needs: sattl-tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        IMAGE: ${{ steps.login-ecr.outputs.registry }}/enrollment-systems/sattl
      run: |
        export TAG=${GITHUB_REF##*/}
        docker-compose build sattl
        docker tag sattl_sattl $IMAGE:$TAG
        docker push $IMAGE:$TAG
        git fetch origin --tags --quiet
        if [ "$(git describe --exact-match --tags 2>/dev/null)" = "$TAG" ]
        then
          docker tag sattl_sattl $IMAGE:prod
          docker push $IMAGE:prod
        fi
