name: SATTL
on: push

jobs:
  tests:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Copy test config
        run: cp .github/workflows/config.json.sample config.json

      - name: Run tests
        run: docker compose run tests

  docker-images:
    needs: tests
    if: |
      always() &&
      !contains(needs.*.result, 'failure')
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/${{ github.repository }}:${{ github.head_ref || github.ref_name }}
          target: base
          push: true
